### PR TITLE
Add autofocus to search bar

### PR DESCRIPTION
**Pull request by AnTheMaker**
Love the project!
This is a minor minor change: I just added autofocus to the search-bar so whenever you open the task menu you can automatically start typing without having to click on the search bar first, just like in the real windows.

### CODE REVIEW

**Comment by PiyushSuthar** [comment]
Thanks for the PR. It looks like we're facing some issues with it.
image

**Comment by Rajaniraiyn** [comment]
> Thanks for the PR. It looks like we're facing some issues with it.
> image

Hey guys my project [windows11](https://github.com/Rajaniraiyn/windows11) also same issue but I fixed it. This is because we focus the search before the Startmenu animation. Try focus after animation using 
`
setTimeout(() => {
                **startmenu**.focus();
            }, **animationduration**)
`

**Comment by PiyushSuthar** [comment]
> > Thanks for the PR. It looks like we're facing some issues with it.
> > image
> 
> Hey guys my project [windows11](https://github.com/Rajaniraiyn/windows11) also same issue but I fixed it. This is because we focus the search before the Startmenu animation. Try focus after animation using
> `setTimeout(() => { **startmenu**.focus(); }, **animationduration**)`

Ohh Great! Thanks for sharing the solution!
In case you wanna give a PR do let me know.

**Comment by Rajaniraiyn** [comment]
No I can't. I doesn't know any frameworks. I am comfortable only with plain JS.

**Pull request closed without merging**
